### ISSUE TITLE
Calibration profile

### ISSUE THREAD

**Issue by seesoe** [jbruce12000/kiln-controller#10]
@jbruce12000 im wondering, what does your comfortably calibrated test-200-250 profile look like when you run it?

**Comment by jbruce12000** [comment]
Initial overshoot of 15 degrees F above the step [note this is with elements full on from cold start], then a drop below the step of 5 or 6 degrees F, then a settle to 1 degree of set after a few cycles.

Swings at low temps are ok for me. At high temps, my kiln is close to set all the time - unless my elements cannot heat fast enough to reach the set point quickly enough. Here are the stats for an actual slow glaze run... https://docs.google.com/spreadsheets/d/1Lcp88P1cNNzYWgKDfnd5UaPVqLuBdAT3lkpfcZMKEBM/edit#gid=2116406322
