### ISSUE TITLE
Kiln-tuner starting and running

### ISSUE THREAD

**Issue by tjerram** [jbruce12000/kiln-controller#109]
I am not sure how to start and run the kiln-tuner.  I assume that I start the kiln-controller in one terminal window and then the kiln tuner in another window but I get an error and a help screen when I try to start the kiln tuner.

Thanks for your help.

**Comment by jbruce12000** [comment]
kiln-tuner.py is a stand-alone process. It heats your kiln to 400 degrees and sees how quickly your kiln reacts to the requested change in temperature. This timing is used to estimate the PID values.

you should read https://github.com/jbruce12000/kiln-controller/blob/master/docs/ziegler_tuning.md

to record the data from the test...

`python kiln-tuner.py recordprofile zn.csv`

to get the PID numbers from the data collected in the step above...

`python kiln-tuner.py zn zn.csv`

If you get stuck or have problems, post the logs using **ziplogs** and I can graph the run and figure out how your PID needs to change.
