### ISSUE TITLE
Please help, I'm about to go insane

### ISSUE THREAD

**Issue by AikoKiss** [jbruce12000/kiln-controller#110]
I have a adafruit 31865 thermal couple amplifier and im trying to get it to work with the software, but when i uncomment libary import, it refuses to work

**Comment by jbruce12000** [comment]
Hi @AikoKiss. Sorry for the frustration. I see you closed this. Today the code supports the MAX-31855 and MAX-31856 amplifiers.

The MAX-31865 is a resistance temperature detector [RTD] and is not currently supported. Is this what you actually have?

**Comment by AikoKiss** [comment]
I have a k type amp

**Comment by AikoKiss** [comment]
but its all good, I managed to make it work!
