### ISSUE TITLE
Small bug in blinka branch

### ISSUE THREAD

**Issue by chipgarner** [jbruce12000/kiln-controller#125]
Missing self.

Line 293 in oven.py
        self.thermocouple = adafruit_max31856.MAX31856(spi, cs) 
should be:
        self.thermocouple = adafruit_max31856.MAX31856(self.spi, self.cs)

**Comment by jbruce12000** [comment]
thanks Chip! change committed to blinka branch.

**Comment by chipgarner** [comment]
Excellent, I have finally made a useful contribution...

**Comment by jbruce12000** [comment]
You go! If you can put up with my cranky demeanor there's room for lots more improvement.
