### ISSUE TITLE
Great project

### ISSUE THREAD

**Issue by steeleh** [jbruce12000/kiln-controller#130]
Jason
A short note to say how very much I appreciate all the work you have put in on kiln-controller. I have two controllers running, one on a MAX31855 and one on a 56. They both run beautifully and are producing some great pottery out of very ancient kilns. If you lived closer I would buy you a series of pints. As it is all you get is a sincere thank you

Steele

**Comment by jbruce12000** [comment]
@steeleh rock and roll! I love to hear when the software is working well in the real world. I hear a lot about problems. It's good to hear about success too.

Also, thanks to everyone who contributes to the project... code, docs, new features, bug fixes. It takes a community.
