### ISSUE TITLE
View Logs 

### ISSUE THREAD

**Issue by rock1148** [jbruce12000/kiln-controller#136]
When the kiln-controller.py autostarts when the rasberry pi boots, the web interface is visible as expected via the IP but how can I see the logs. Do I need to somehow connect to the kiln-controller process?

Otherwise, I have everything working perfectly.

**Comment by jbruce12000** [comment]
See... https://github.com/jbruce12000/kiln-controller/blob/master/docs/logs.md

You have to login to the RPi. Change directories to /var/log/. Edit the file daemon.log.

**Comment by jbruce12000** [comment]
closing. re-open if this did not solve your issue about finding logs.
