### ISSUE TITLE
Random no connection with max31856 and quits

### ISSUE THREAD

**Issue by MeltTechAu** [jbruce12000/kiln-controller#137]
I have a max31856 actually a few of them they don’t seem to work with jbruces software they spit out random no connection which quits program I know I can ignore error but then the issue of thermocouple breaking and melting down your kiln hmm jbruce how do we fix this issue how to stop it going into emergency quit

**Comment by rondoc** [comment]
I have used both 31856 and 31855. Both work well with original pi etc.
Problem with both is that the thermocouple MUST be really floating. No
connection to ground!! Also the 55 seems to be very stable and the 56 seems
more sensitive to electrical noise.
R.

**Comment by jbruce12000** [comment]
@chipgarner any updates on the max-31856 or adafruit libs?

**Comment by jbruce12000** [comment]
Sorry @chipgarner, I think we've explained @MeltTechAu max-31856 issues. I'm gonna close this.
