### ISSUE TITLE
relay behaving opposite of intended.

### ISSUE THREAD

**Issue by sactheskydiver** [jbruce12000/kiln-controller#141]
when I first load the server my heater turns on and will stay on until I start a firing schedule, my relay acts opposite to the program and im not sure what to do :/ 

 INFO oven: temp=125.79, target=149.06, error=23.27, pid=0.00, p=581.63, i=-0.10, d=0.00, heat_on=5.00, heat_off=0.00, run_time=5, total_time=49, t

when it reads like this the SSR and heater turns OFF

INFO oven: temp=126.83, target=65.00, error=-61.83, pid=0.00, p=-1545.74, i=0.00, d=0.00, heat_on=0.00, heat_off=5.00, run_time=0, total_time=54600, time_left=54599

and when it reads "heat_off= 5.00" then it turns my SSR on. 

swapping the lines obviously doesnt work so im just stuck :(

**Comment by chipgarner** [comment]
This is a wiring or relay type issue of some kind. Some relays are normally on, some can be changed from on to off. 

Someone here, maybe even me, can help but we need to know more about your relay and how it is connected to power and logic.

**Comment by sactheskydiver** [comment]
Me and chatGPT figured out to just swap gpio.HIGH and gpio.LOW in the oven.py file definition and it works great now! Testing my first piece of stoneware in the kiln now!
