### ISSUE TITLE
state.json: excessive sd card writes

### ISSUE THREAD

**Issue by thadwald** [jbruce12000/kiln-controller#143]
This is not a real issue in the sense that I have not experienced any problems with it. But given the issue with sd card wear, it could become one? 

This controller writes a several-kB json file to disk at every controller period. Is there a simple way to avoid this?

**Comment by jbruce12000** [comment]
The reason this happens is to persist state so restarts after a power outage [or manual stoppage] are possible.

The only time this file is written is if 

`automatic_restarts = True`

So, set that to **False** and the file will no longer be written.
