### ISSUE TITLE
 catchup mode will kiln switch off if it can't obtain the temperature?

### ISSUE THREAD

**Issue by MeltTechAu** [jbruce12000/kiln-controller#152]
will it switch off if it cant obtain temp so as if to work for worn out elements?
 just firing taking longer then switch off?
like a cone mode sort off ? just a few questions ?

**Comment by jbruce12000** [comment]
Will it switch off automatically if my elements are worn out and my temperature cannot be obtained?

`No`

or will it just keep attempting to reach that temperature forever?

`Yes. If you have the setting kiln_must_catch_up=True, the kiln will wait forever for the current temp to be achieved.`
`Yes. If you have the setting kiln_must_catch_up=False, the kiln will continue the profile trying to reach the temp at each second of the profile until it ends... then the kiln-controller would exit.`

Like a cone mode sort of?

`No. A cone mode would imply that some sort of heat-work-over-time measurement is being kept, stored, and tracked. This does not happend.`

More questions? ask away.

I'm gonna close this. Open a new issue if you have one.

**Comment by jbruce12000** [comment]
closing...
