### ISSUE TITLE
Cone MODE Feature Nearly Going ,! need a hand with buttons on front end Anyone??? So close Jbruce 

### ISSUE THREAD

**Issue by MeltTechAu** [jbruce12000/kiln-controller#162]
https://github.com/MeltTechAu/kiln-controller/tree/Cone-Mode

i had it work once it ended run but then started new timer it did this only once Not tested on kiln just did a run at ambient
it will activate under certain circumstances but buttons not working

Any coders got experience with front end UPDATE  button not defined or just not working this is what i need a hand with if anyone's keen let me know would be awesome to be up there with this awesome feature everyone wants especially for worn out elements

Anyhow let me know i will keep trying just thought one of you experience coders might have a clue see button/UPDATE at bottom of screen index html  so its currently not updating cone selections
This feature will make this software up there with the best of them that's what i want too hope you guys do too
CONE LIST MUST BE UPDATED VIA THE UPDATE BUTTON AT BOTTOM OF INDEX FILE CONE MODE SET DOESNT SEEM TO WORK FOR SOME REASON ALSO MUST BE ACTIVATED WHICH BUTTON SEEMS TO DO NOTHING :(

Would be an awesome upgrade to this software
ill keep at it but need help pretty please
Cheers Brett

**Comment by jbruce12000** [comment]
I think if someone wants to tackle cone mode, it should be a fork.
