### ISSUE TITLE
Cone mode needs help a real programmer can finish it

### ISSUE THREAD

**Issue by MeltTechAu** [jbruce12000/kiln-controller#170]
I’m not it who is I have left it as a running project I have so much more to give just need a hand I’ve sold 6 completed projects so can u do the same I’m broken just like cone mode life has got the better of me but for this project I will continue  as a kiln tech that I am I even built a kiln around this project for commercial purposes I hope one of you can make it happen we are all the same let’s better this world like Brett Beauregard wanted it’s 15 years old and I believe selling Bartlett stuff all my life that this is it it’s been hard to convince the public that we have one of the most accurate controllers around let’s make it no 1 which it is in testing I will plug along but I need your help who ever gets cone mode happening  gets 10% of all MeltTechau profits I’m also going to add we are going to add things like which are needed profile identification so our lists are in order and speed control I want u jbruce mark to lies chip garner and the list goes on who is the best of the best I need u I have a kiln outlet and kilns will be named after the legend that can give us this no stress at all I have done most of the work I hope it is right the right person will know all the ins and outs as now I’m pretty fluent in all aspects remember 10 percent for some tech work I’m sure u guys are capable in anyone interested add me to facebook Brett probert we have a an Australian outlet which I’m building on just need cone mode like the others and it will sell that’s roughly $100 per sale au contact to be sent and signed before I even get to know you got it going I trust the boys and gals on here Bartlett can be 1/2 a cone to a full cone out before offset has been set we want it perfect I have made it only to do that with an estimate if data does not flow as expected only I want perfection unlike the others contact me now let me know remember I have have done some serious work I hope it makes it easy as 10 % of all income it’s a pretty good deal mark where r u I like that it can do multiple kilns as well I have filled u through this as much as jbruce and chip garner we will worry about multi zone soon as as a business we only sell single zone but like mark has made our customers want that 2 one controller that does it alll enough said who’s interested send me a pm
Jbruce were ready to change the world for the better smokers , sous chef pizza chickens for food mining companies I work with them all in my day job I have the in’s also a hydroponics controller and wot ever pi has to offer one controller that does it all to the right person o will share our future from kiln controller to full house hold controlller just like kbruce invisioned i seee it in i really do hope in gets you get on board iplease replay do let’s just make it happen please be the one check out AAKilns.com.au i built a kiln around this i will start is sales soon
One controller that does it all help me I will help u that’s a deal with MeltTech.com.au we can do this I smart but only learnt in three weeks to be the programmer we can do this together that’s what free ware is about and dam I am offering hope that’s enough I do 2 jobs now full time I believe in this project and have put in over 40000 so far because it is better than the rest I box up Bartlett by day that are just crap compared to this let’s box up MeltTechs and so on 10 inch touch screeen controllers Aussie market has been drummed into but with element worn cone mode sales are not there for ramp hold even though we are not limits by ramps and soaks etc I run this program daily testing and it just works let’s cone mode and beyond yes 10 % can be yours if I sell 50 controllers that’s 50 grand less your 10 let’s do this who wants an income with just using your extrodinary talents it could earn you a percent job doing stuff all please contact me now who wants this just start by looking at my cone mode version nearly done it might be the easiest money you have ever earned as a programmer contract will be drawn up to the right person let’s do this

**Comment by jbruce12000** [comment]
I think if someone wants to tackle cone mode, it should be a fork.
