### ISSUE TITLE
[Feature Request] Make usable for wood kiln by adding hygrometer input <-> on/off dehydrator output

### ISSUE THREAD

**Issue by u2n** [jbruce12000/kiln-controller#176]
No PID logic needed (moisture changes slowly), just setpoint and deadband. Could make this an all-kiln controller.

**Comment by jbruce12000** [comment]
I feel that controlling a wood fired kiln is out of scope for this project. It is so radically different than an electric fired kiln that most of the code and settings would go unused [or be completely different]. The inputs and the harware used to measure them are different.
