### ISSUE TITLE
Auto tune issue

### ISSUE THREAD

**Issue by MeltTechAu** [jbruce12000/kiln-controller#182]
When trying to autotune  as per instructions it says can not import config adapt it copy examaple config but the kiln controller runs fine any thoughts jbruce im moving to the max 31856 and the new blinka software please help again thank you for your valued time
cheers brett from melttech

**Comment by och29** [comment]
I'm getting the same error. My process:
 - From a clean boot (with autostart turned on)
 - Confirm web interface is active, thermocouple and SSR are functional (using pre-built scripts)
 - Via SSH `systemctl stop kiln-controller`
Output:
```

pi@kilnpi:~/kiln-controller $ systemctl stop kiln-controller
==== AUTHENTICATING FOR org.freedesktop.systemd1.manage-units ====
Authentication is required to stop 'kiln-controller.service'.
Authenticating as: ,,, (pi)
Password:
==== AUTHENTICATION COMPLETE ====
pi@kilnpi:~/kiln-controller $ python kiln-tuner.py recordprofile zn.csv
Could not import config file.
Copy config.py.EXAMPLE to config.py and adapt it for your setup.
pi@kilnpi:~/kiln-controller $
```

config.py is present in the folder
```
pi@kilnpi:~/kiln-controller $ ls
config.py           kiln-tuner.py  requirements.txt  test-output.py
docs                lib            start-on-boot     test-thermocouple.py
gpioreadall.py      public         state.json        venv
kiln-controller.py  __pycache__    storage           watcher.py
kiln-logger.py      README.md      Test              ziplogs
```

**Comment by jbruce12000** [comment]
can one of you comment out the try/except block near the top of kiln-tuner.py?
post the error.

What I'll likely do is remove this try/except block so that folks can see what the real error is.

**Comment by och29** [comment]
> can one of you comment out the try/except block near the top of kiln-tuner.py? post the error.
> 
> What I'll likely do is remove this try/except block so that folks can see what the real error is.

```
pi@kilnpi:~/kiln-controller $ python kiln-tuner.py recordprofile zn.csv
usage: kiln-tuner.py [-h] [-c] [-t TARGET_TEMP] [-d TANGENT_DIVISOR] [-s]
kiln-tuner.py: error: unrecognized arguments: recordprofile zn.csv
```

**Comment by MeltTechAu** [comment]
Confirmed getting same error och29

**Comment by jbruce12000** [comment]
This is an old branch and old version. you need to grab the latest code. I did a simulation on the head of the main branch and found a bug... then fixed it.

**Comment by MeltTechAu** [comment]
Getting same error with fresh dl today????

**Comment by jbruce12000** [comment]
post the output of:

```source venv/bin/activate
./kiln-tuner.py
```
The kiln-tuner parameter handling was changed last Dec and should no longer be called like it is above.

**Comment by jbruce12000** [comment]
The _master_ branch is no longer supported. The _main_ branch is now the active, supported branch. Switching branches may cause you some configuration or hardware re-work.

**Comment by och29** [comment]
Ah, then it's an issue with the link here then! https://github.com/jbruce12000/kiln-controller?tab=readme-ov-file#pid-tuning

**Comment by jbruce12000** [comment]
fixed the README. All links that pointed to _master_ or _blinka_ now point to _main_.

good find. lemme know if tuning still does not work for you.

**Comment by MeltTechAu** [comment]
Legend jbruce thank you so much have a great day mate!

**Comment by jbruce12000** [comment]
@MeltTechAu how did that tuning work out? any problems?

**Comment by jbruce12000** [comment]
closing. create a new issue if you find a new problem with the code or docs.

**Comment by och29** [comment]
I have tested this now, confirmed solved.
