### ISSUE TITLE
Are you interested in my kiln display code?

### ISSUE THREAD

**Issue by adq** [jbruce12000/kiln-controller#19]
Hi, I'm not submitting this as a merge request yet. I was just wondering if you would be interested in me doing so?

I bought one of these for my pi: https://www.adafruit.com/product/4484

I wrote software talking to the exsting websocket API: https://github.com/adq/kiln-controller/blob/kilndisplay/kiln-display.py
(The buttons do not do anything right now)

Retrofitted to my kiln (replacing the original 3 button controller) , it looks like this (running the 200/250 test profile):  ![kilnlcd](https://user-images.githubusercontent.com/322473/115302509-69daaf00-a15a-11eb-88bc-4a35ea8da2ad.jpg)

Main problem is I had to shift the GPIOs along to make room for the LCD.

**Comment by jbruce12000** [comment]
cute. so small. so it shows schedule, elapsed time, time left and current temp (not set point, but actual)?

**Comment by jbruce12000** [comment]
I see some libs in that code that are not used anywhere else. When you submit a PR, make sure to modify requirements.txt and docs.

**Comment by adq** [comment]
Awesome. willdo!

Yeah, its just the current temp. Good call about the setpoint; will add it before MR!

**Comment by adq** [comment]
Created an MR, so closing this issue.
