### ISSUE TITLE
Offset in the Config.py

### ISSUE THREAD

**Issue by Steve1445** [jbruce12000/kiln-controller#2]
My thermocouple is reading 10 degrees F low. Before I run out and buy another I would like to use the offset line in the Config.py.  I have set this to 10 (actually to several positive and negative  numbers) all without any impact the measured temp displayed in the sensor temp box. 

Is there more to this than just changing the line I referred to or is this something not enabled.

**Comment by jbruce12000** [comment]
I implemented this, but you should double check polarity of the thermocouple connection and the thermocouple wire.  Polarity matters.  If you get both connections backward like I did, it results in an offset.  Also could be a low cost thermocouple.
