### ISSUE TITLE
RPI.GPIO not compatible with pi5

### ISSUE THREAD

**Issue by PierreMagreesource** [jbruce12000/kiln-controller#201]
Hello,

I tried installing this on a Raspberry pi5 and it didn't work, i got "RuntimeError : Cannot determine SOC peripheral base address" when trying to run ./test-thermocouple.py and ./test-output.py.

After a quick internet search for this error, i learned that RPI.GPIO does not work with the pi5 because of hardware changes.

I made this issue to notify you as i thought you might want to add this to your README.

**Comment by chipgarner** [comment]
@PierreMagreesource 

This might work:
sudo apt remove python3-rpi.gpio
pip3 install rpi-lgpio

**Comment by PierreMagreesource** [comment]
@chipgarner 

There was no gpio module to remove both in the general and virtual environment, but i was able to install rpi-lgpio in the virtual environment, and the two tests now work.

Thank you.

**Comment by jbruce12000** [comment]
excellent. glad you got this to work. nice job @chipgarner!
