### ISSUE TITLE
Query about pid tuning instructions

### ISSUE THREAD

**Issue by adq** [jbruce12000/kiln-controller#22]
In the instructions it says:

> * If the temp is always below the set point, increase pid_ki.

But in the code/ config.py, it says:

>Note that the integral pid_ki is inverted so that a smaller number means more integral action.

I am very new to PID, but are the tuning instructions correct that **increasing** pid_ki will help the below-set-point problem given it is inverted?

**Comment by jbruce12000** [comment]
yep. bug. I made the change to the code, but not the docs. fixing now.
