### ISSUE TITLE
Another Question about pid_tuning document 

### ISSUE THREAD

**Issue by adq** [jbruce12000/kiln-controller#25]
Hi, I think I may have spotted an issue with the PID tuning instructions (though I could very well be wrong!) . 

From my other reading, the general concept is to disable the PID completely, turn the kiln on at full power, observe the kiln's behaviour for a while and then derive the Kp/Ki/Kd from the temperature profile.

In the instructions, I assume this is what the following is doing:
```
in config.py set the PID values like so...

    pid_kp = 1.0
    pid_ki = 0.0
    pid_kd = 0.0
```

Unfortunately recent changes to the codebase mean this is not in fact disabling the PID completely. If you look at the PID code, it does the following to calculate the power output `out` (with the above settings):

1. Calculate error
2. Multiply error by `Kp` == 1.0
3. Clamp to the range 0 -> 100.
4. Divide by 100 (the window_size).

So, say you're 42 degrees away from the target temperature. The above algorithm will calculate:

> out = (42 * 1) / 100 == 0.42

So I think the PID is in fact actively affecting the power in the last 100 degrees stretch. You'd need to have a Kp of 100 to disable it completely. (technically that would still affect results where abs(error) < 1.0, but I think we can live with that :)

**Comment by jbruce12000** [comment]
The idea is not to disable the PID. The idea is to have just Proportional active. With just Proportional, it will shoot past the setpt a certain amount and shoot past the setpt going the other way. The amount of time it takes helps set the Derivative, any needed offset helps define the Integral.

I checked in the code for Integral windup last night. Try that code out and report back. Search for windup in config.py.
