### ISSUE TITLE
config not imported

### ISSUE THREAD

**Issue by artcank** [jbruce12000/kiln-controller#33]
I am having an issue where it says it can't import the config file and that I need to copy it from the example. Even though I have done that and changed what I needed to in it.

I am using the latest rasbian BTW.

**Comment by jbruce12000** [comment]
Are you running on a raspberry pi? Are you running a simulation? Are you using max31855 or max31856? did you pip install the requirements you need for your hardware?

**Comment by artcank** [comment]
Running on raspberry pi following all the installation
requirements/procedures. I am using a max31856.

**Comment by jbruce12000** [comment]
ok. Can you post the log? should be sent to /var/log/syslog

**Comment by artcank** [comment]
[syslog.txt](https://github.com/jbruce12000/kiln-controller/files/6717693/syslog.txt)

**Comment by artcank** [comment]
![Error](https://user-images.githubusercontent.com/75939150/123527379-a075fe00-d6a4-11eb-9497-46261ffe92e7.jpg)

I switched to another raspberry pi and I was able to read my GPIO's but when I tried to run the config.py file I got this error:
ModuleNotFoundError: No module named 'Adafuit_GPIO'

**Comment by jbruce12000** [comment]
open a shell and...

```
source venv/bin/activate
pip install Adafruit-GPIO
```

**Comment by artcank** [comment]
That didn't work but I was able to follow the instructions on adafruit's github_GPIO page and get that installed. Then it said I didn't have RPi.GPIO installed. I got that installed and it WORKED!

It is reading my S type sensor!!! 

Now to get the SSD wired up and make a box to install on the kiln.

Thanks

**Comment by jbruce12000** [comment]
ok. I'm interested to see what you did so I can change instructions if needed. Did you keep a log of the commands you ran? Were you using a virtualenv?

**Comment by jbruce12000** [comment]
glad you got it working though. I think you're the third one to get an s-type thermocouple working with a max-31856. congrats!

**Comment by jbruce12000** [comment]
assuming you're not tracking this. closing. lmk if you have some details I should change in the docs.

**Comment by artcank** [comment]
Okay.
I had it working on a temp breadboard but when I made a soldered board it's not working again... Trying to troubleshoot and get it figured out.

**Comment by artcank** [comment]
Got it running on the kiln today! Trying my first bisque fire. I had trouble like someone else with the GPIO numbering but that is now sorted. I'll look at the data to try and tune the PID later.

I had a thought while getting it up and running headless on the kiln, how hard would it be to put a shutdown/reboot RaspberryPi button on the web page? Also maybe a Restart Kiln-Controller
