### ISSUE TITLE
question about wiring and operation

### ISSUE THREAD

**Issue by heridfel** [jbruce12000/kiln-controller#36]
Hey, first of all, looks like great work!

Perhaps a naive question, but looks like you are just wiring the SSR on one of the hot legs between the power outlet and your kiln sitter. Is this correct? I have a 220V 40A kiln with six elements and six control knobs. In this case do you just set all knobs to max and let the controller flip the SSR on and off as needed?

**Comment by jbruce12000** [comment]
My 3 phase ssr controls all power to all elements so it is binary on or off only. I have all knobs set to max. This gives the SSR complete control over all elements with max output. This is what you should do.
