### ISSUE TITLE
Shutting down the Pi

### ISSUE THREAD

**Issue by secretbadger** [jbruce12000/kiln-controller#57]
I am curious to find out if it is considered detrimental to just pull the power to powerdown the RPi as there is no easy way to shut the system down without having a screen plugged into the RPi.

I know in the past I have wrecked the software on an SD card from simply pulling the power lead. !

As you can tell I am a software novice. 

Many thanks to all. Totally brilliant project. Look forward to powering up the kiln very soon.

**Comment by jbruce12000** [comment]
The RPi OS uses the ext4 journaling filesystem by default. I have pulled the plugged on my RPi's many times and I have never had a problem. Is it a good idea? probably not. Will it break your system? almost never.
