### ISSUE TITLE
Heat on icon

### ISSUE THREAD

**Issue by steeleh** [jbruce12000/kiln-controller#58]
Current clean install on pi Zero linked to a MAX31856 board. The red .ds-led-heat-active icon only flashes on once (for about a second) per duty cycle even if the whole cycle is logged as 'heat on'. Tested lengthening duty cycle to 20 secs and red heat on icon still only flashes on once per cycle. 

Any thoughts on where I should look?

**Comment by jbruce12000** [comment]
A websocket is opened with every client. In lib/oven.py, the state gets set and sent to each client every sensor_time_wait seconds (every 2s by default in config.py). The state variable named heat is the one you want. The state is received by the client and handled in picoreflow.js... see line 563. This is where the decision is made to turn on the icon and for how long.

Feel free to fix this code and submit a PR if you get something that works well. I have struggled with the best way to handle this in the past. Maybe just better to display the value of the heat variable on the client.

**Comment by marktilles** [comment]
>>>SNIP<<<<
Maybe just better to **display the value of the heat variable on the client**.

I will, with my programmer friend Marko Burazin's assistance, be submitting a pull request that displays the heating % on the client. It will flash the heating icon yellow, if heating at anything less than full capacity, in which case the icon will blink red.

But we are hoping to see our "future scheduling" mod already submitted tested and integrated first
![Screen Shot 2022-01-03 at 00 09 15](https://user-images.githubusercontent.com/82381104/147891869-fa26852a-7df8-468d-8b93-aed1515ab061.png)
.

**Comment by jbruce12000** [comment]
gotcha. I just commented on the scheduling thing. I use the api to achieve that. comments welcome.

**Comment by marktilles** [comment]
> gotcha. I just commented on the scheduling thing. I use the api to achieve that. comments welcome.

Then I’m a little confused, does this mean you do not want to integrate it into your branch?

**Comment by steeleh** [comment]
Reformated SD card and reinstalled from scratch. Seems to have worked.
