### ISSUE TITLE
Illegal Instruction error on Pi Zero W

### ISSUE THREAD

**Issue by tanaes** [jbruce12000/kiln-controller#61]
I'm getting an `Illegal instruction` error when trying to run this on a Pi Zero W. I think this is most likely due to an ARMv6 / ARMv7 compilation issue in one of the dependencies, but little to no clue which one is the culprit! 

I have a Pi Zero W2 I will try on, which shares the CPU with the Pi 3b. Will report back!

**Comment by tanaes** [comment]
Running on Pi Zero W2 does seem to fix it!

**Comment by jbruce12000** [comment]
hey @tanaes seems like you have a work-around. closing this until we get more detail. I don't own any rpi-zeros, so I cannot test.
