### ISSUE TITLE
Controlling an Fan on specific Timepoint

### ISSUE THREAD

**Issue by Shinjaii** [jbruce12000/kiln-controller#73]
Hello, I want to use this Kiln-Controller for as an Controller for an Powder Oven.
My quesion is, is it possible to acivate a fan at a specific time? Because it can't run at the beginning because it would just blow the powder from the object. I would like to get it up to 150 Celcius using the fan then when hitting 150 deactivating the fan for about 5-10 min and then acivate the fan again.

Im sorry for my broken english and im a noob in  programming.
Thanks for the help :))

**Comment by jbruce12000** [comment]
This is a fork of picoreflow and cooling has been removed. you probably should use that if you're interested in cooling.

**Comment by Shinjaii** [comment]
I can't Install picoreflow because the Code to Install IT Always gives me failures ... I think its because it is to old
