### ISSUE TITLE
Max31855 calibration

### ISSUE THREAD

**Issue by alrpal** [jbruce12000/kiln-controller#8]
Hi there. Great library. I built my own kiln and have been playing with this. I’ve run into a problem where my k type thermocouple is drastically under reporting the temperature. The end result is my metal clay that should be sintering at 1500f are turning into spheres of metal land I’m burning out heating elements. I’m going to get a new thermocouple but wondering how I can take some test voltages at known temperatures and integrate that into the max31855 code. I looked through max31855.py but not sure how I’d modify it for a calibration curve.

**Comment by jbruce12000** [comment]
Hi alrpal,

It sounds like your thermocouple is way off! burning out elements sucks.

I grabbed the linearization code directly from https://github.com/nightmechanic/FuzzypicoReflow/blob/master/lib/max31855.py unmodified. I'm not sure what you would need to do to modify this curve to match the output of your specific thermocouple.

I think it would be best to wait until the new thermocouple arrives. test it at room temp. test it at near freezing in ice water to verify it is close. if you have something like an oven thermometer, you can use that in conjunction with your new thermocouple to verify it is reading accurately at higher temperatures.  Oven thermometers go to 550F at least here in the US.

The K type thermocouple I use cost about $30 and with tests above it is always spot on...
https://www.auberins.com/index.php?main_page=product_info&cPath=20_3&products_id=39
