### ISSUE TITLE
web clients join and temps go down

### ISSUE THREAD

**Issue by jbruce12000** [jbruce12000/kiln-controller#85]
over the course of 20s seconds or so when a new web client joins the server, something is causing the temperature read at the thermocouple to do down by 20 or more degrees. This causes the current temp to go out of the PID control window... which causes 100% heating to the kiln for that period. This causes a temperature spike in the kiln - which for me at 250F was about 10F.

Figure out the cause, put debugging on the thermocouple reads. fix it.

**Comment by jbruce12000** [comment]
@rondoc 31855

**Comment by rondoc** [comment]
I am not sure but I think that my system always starts at 100% when
setpoint is higher than ambient. Then overshoot is inevitable )))

**Comment by jbruce12000** [comment]
renice of the kiln-controller to the highest priority has no impact. Even more drastic temperature drops happen if I do something like scp a large file from the rpi to another box. It seems like any process that takes up significant cycles may cause this problem.

**Comment by jbruce12000** [comment]
this is a problem even if only a single value is read during the duty cycle. I don't think there is anything I can do about this.

**Comment by captaincaden** [comment]
I don't experience this issue, and when the kiln is running, I frequently have been known to exit and rejoin the server multiple times throughout a firing.
I'm using the max31856 board.

**Comment by jbruce12000** [comment]
this is also the first time I have experienced this issue. my guess is that it is kernel related, but I have not tried to track down the cause. since renice doesn't fix it, it's unlikely a process scheduler problem.
