### ISSUE TITLE
How to stop server/program from running

### ISSUE THREAD

**Issue by umfan92** [jbruce12000/kiln-controller#88]
Hey @jbruce12000  Sorry, this isn't an issue with the code. It's more of an issue with my lack of coding knowledge. 

I'm trying to reinstall the new updates but since the old version is running on auto-boot, it's currently still running. I deleted the folder and I rebooted it but the old server still starts up.

When I try to start up the server I get an error stating "Address already in use".

How do wipe it so that it doesn't restart the server on boot?

Also, for general troubleshooting, how would you stop the server from running once it's already started? I haven't been able to figure that out.

**Comment by umfan92** [comment]
I used "ps -ef | grep python" and found the pid of the process and then used "kill <PID>" to kill it. Found those commands on [this page](https://forums.raspberrypi.com/viewtopic.php?t=71108).

But is there a better way to kill the server once it's running?

**Comment by jbruce12000** [comment]
You're looking for this...

`sudo service kiln-controller restart`

Raspberry PI OS uses systemd to manage daemons. The above command is an old school throw-back to systemd's predecessor called init. Anyway, here's a link if you want more details...

https://www.techrepublic.com/article/how-to-start-stop-and-restart-services-in-linux/

To stop the server from automatically starting at boot...

`sudo systemctl disable kiln-controller`

but I wouldn't do that. I like it to start automagically.

**Comment by umfan92** [comment]
Is there a similar command to stop it rather than restart it? 

Not to stop the auto-start but to just kill it temporarily?
