### ISSUE TITLE
Direct temperature input

### ISSUE THREAD

**Issue by masterjuggler** [jbruce12000/kiln-controller#9]
Hi, I'm looking into using this for a heat treat oven I have. Would it be possible to add a field for direct temperature input, or to make the target temp field editable when not running a schedule? It would make it a lot easier to harden and temper steel when there are many different set points, each individual one used infrequently. It would also allow for easier preheating.

**Comment by jbruce12000** [comment]
The idea behind schedules is that you can create a different schedule for each unique tempering cycle. Say each type of steel you want to temper has a different max tempering peak and hold time. You could create each one individually using the web interface (slow) or you can do this much faster by creating the first one in the web interface and then copying it on the command line.

These files are located in kiln-controller/storage/profiles/.  Copy the one you created and modify it by changing the max temp and the soak time. You could create hundreds of these if you wanted. Each with it's own unique tempering cycle.

I don't think having an override input box for setting the temperature is something I want to do design wise. If you choose to do this, you can fork the project and go for it.
