### ISSUE TITLE
Maybe an API call to write memos to the log?

### ISSUE THREAD

**Issue by maabaum** [jbruce12000/kiln-controller#94]
This really isn't an issue so much as a suggestion. I wonder about writing an additional API call along the lines of:

`
    # this new API command allows you to send a memo line to the log file
    # that will be timestamped -- so for example opening the kiln lid
    # to rapidly cool or something

    if bottle.request.json['cmd'] == 'memo':

        msg = bottle.request.json['msg']

        log.info('memo: %s' % msg)
`

There are almost certainly errors in that, but the idea, as stated, would be to allow the user to write time-stamped memoranda lines into the log file to note events that might be import for later diagnostics.

**Comment by jbruce12000** [comment]
added. please test. I tested and seems ok.

**Comment by maabaum** [comment]
Seems to work fine. Thanks!!
